// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.3
// source: metadata.proto

package metadata

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginMetadata_GetInfo_FullMethodName = "/metadata.PluginMetadata/GetInfo"
)

// PluginMetadataClient is the client API for PluginMetadata service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginMetadataClient interface {
	GetInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error)
}

type coreMetadataClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginMetadataClient(cc grpc.ClientConnInterface) PluginMetadataClient {
	return &coreMetadataClient{cc}
}

func (c *coreMetadataClient) GetInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginInfo)
	err := c.cc.Invoke(ctx, PluginMetadata_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginMetadataServer is the server API for PluginMetadata service.
// All implementations must embed UnimplementedPluginMetadataServer
// for forward compatibility.
type PluginMetadataServer interface {
	GetInfo(context.Context, *Empty) (*PluginInfo, error)
	mustEmbedUnimplementedPluginMetadataServer()
}

// UnimplementedPluginMetadataServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginMetadataServer struct{}

func (UnimplementedPluginMetadataServer) GetInfo(context.Context, *Empty) (*PluginInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedPluginMetadataServer) mustEmbedUnimplementedPluginMetadataServer() {}
func (UnimplementedPluginMetadataServer) testEmbeddedByValue()                        {}

// UnsafePluginMetadataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginMetadataServer will
// result in compilation errors.
type UnsafePluginMetadataServer interface {
	mustEmbedUnimplementedPluginMetadataServer()
}

func RegisterPluginMetadataServer(s grpc.ServiceRegistrar, srv PluginMetadataServer) {
	// If the following call panics, it indicates UnimplementedPluginMetadataServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginMetadata_ServiceDesc, srv)
}

func _PluginMetadata_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginMetadataServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginMetadata_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginMetadataServer).GetInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginMetadata_ServiceDesc is the grpc.ServiceDesc for PluginMetadata service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginMetadata_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metadata.PluginMetadata",
	HandlerType: (*PluginMetadataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _PluginMetadata_GetInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metadata.proto",
}
