// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.3
// source: dsc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DSCPluginService_Name_FullMethodName        = "/dsc.DSCPluginService/Name"
	DSCPluginService_Version_FullMethodName     = "/dsc.DSCPluginService/Version"
	DSCPluginService_Execute_FullMethodName     = "/dsc.DSCPluginService/Execute"
	DSCPluginService_HealthCheck_FullMethodName = "/dsc.DSCPluginService/HealthCheck"
)

// DSCPluginServiceClient is the client API for DSCPluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DSCPluginServiceClient interface {
	Name(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*NameResponse, error)
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type dSCPluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDSCPluginServiceClient(cc grpc.ClientConnInterface) DSCPluginServiceClient {
	return &dSCPluginServiceClient{cc}
}

func (c *dSCPluginServiceClient) Name(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*NameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NameResponse)
	err := c.cc.Invoke(ctx, DSCPluginService_Name_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSCPluginServiceClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, DSCPluginService_Version_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSCPluginServiceClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, DSCPluginService_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSCPluginServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, DSCPluginService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DSCPluginServiceServer is the server API for DSCPluginService service.
// All implementations must embed UnimplementedDSCPluginServiceServer
// for forward compatibility.
type DSCPluginServiceServer interface {
	Name(context.Context, *NameRequest) (*NameResponse, error)
	Version(context.Context, *VersionRequest) (*VersionResponse, error)
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedDSCPluginServiceServer()
}

// UnimplementedDSCPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDSCPluginServiceServer struct{}

func (UnimplementedDSCPluginServiceServer) Name(context.Context, *NameRequest) (*NameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Name not implemented")
}
func (UnimplementedDSCPluginServiceServer) Version(context.Context, *VersionRequest) (*VersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedDSCPluginServiceServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedDSCPluginServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedDSCPluginServiceServer) mustEmbedUnimplementedDSCPluginServiceServer() {}
func (UnimplementedDSCPluginServiceServer) testEmbeddedByValue()                          {}

// UnsafeDSCPluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DSCPluginServiceServer will
// result in compilation errors.
type UnsafeDSCPluginServiceServer interface {
	mustEmbedUnimplementedDSCPluginServiceServer()
}

func RegisterDSCPluginServiceServer(s grpc.ServiceRegistrar, srv DSCPluginServiceServer) {
	// If the following call panics, it indicates UnimplementedDSCPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DSCPluginService_ServiceDesc, srv)
}

func _DSCPluginService_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSCPluginServiceServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DSCPluginService_Name_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSCPluginServiceServer).Name(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSCPluginService_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSCPluginServiceServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DSCPluginService_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSCPluginServiceServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSCPluginService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSCPluginServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DSCPluginService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSCPluginServiceServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSCPluginService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSCPluginServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DSCPluginService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSCPluginServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DSCPluginService_ServiceDesc is the grpc.ServiceDesc for DSCPluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DSCPluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dsc.DSCPluginService",
	HandlerType: (*DSCPluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Name",
			Handler:    _DSCPluginService_Name_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _DSCPluginService_Version_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _DSCPluginService_Execute_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _DSCPluginService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dsc.proto",
}

const (
	AgentService_Run_FullMethodName                     = "/dsc.AgentService/Run"
	AgentService_RunStream_FullMethodName               = "/dsc.AgentService/RunStream"
	AgentService_Name_FullMethodName                    = "/dsc.AgentService/Name"
	AgentService_Version_FullMethodName                 = "/dsc.AgentService/Version"
	AgentService_RegisterServices_FullMethodName        = "/dsc.AgentService/RegisterServices"
	AgentService_SwitchSession_FullMethodName           = "/dsc.AgentService/SwitchSession"
	AgentService_SetPlanMode_FullMethodName             = "/dsc.AgentService/SetPlanMode"
	AgentService_SetUserQuestionsService_FullMethodName = "/dsc.AgentService/SetUserQuestionsService"
	AgentService_Shutdown_FullMethodName                = "/dsc.AgentService/Shutdown"
	AgentService_InjectMessage_FullMethodName           = "/dsc.AgentService/InjectMessage"
	AgentService_DebugSnapshot_FullMethodName           = "/dsc.AgentService/DebugSnapshot"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
	RunStream(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunStreamResponse], error)
	Name(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*NameResponse, error)
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
	RegisterServices(ctx context.Context, in *RegisterServicesRequest, opts ...grpc.CallOption) (*RegisterServicesResponse, error)
	SwitchSession(ctx context.Context, in *SwitchSessionRequest, opts ...grpc.CallOption) (*SwitchSessionResponse, error)
	SetPlanMode(ctx context.Context, in *SetPlanModeRequest, opts ...grpc.CallOption) (*SetPlanModeResponse, error)
	SetUserQuestionsService(ctx context.Context, in *SetUserQuestionsServiceRequest, opts ...grpc.CallOption) (*SetUserQuestionsServiceResponse, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	// InjectMessage 将一条用户消息实时注入到当前运行的会话历史末端：
	// 模型在下一次 LLM 迭代即可看到，无需停止或等待本轮完成。
	InjectMessage(ctx context.Context, in *InjectMessageRequest, opts ...grpc.CallOption) (*InjectMessageResponse, error)
	// DebugSnapshot 返回 agent 当前运行时的调试快照：会话历史（含实时注入的消息）、
	// token 用量、turn 计数与 plan/goal 状态。供 ADMIN API DEBUGGER 端点与自动化测试观察。
	DebugSnapshot(ctx context.Context, in *DebugSnapshotRequest, opts ...grpc.CallOption) (*DebugSnapshotResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, AgentService_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RunStream(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_RunStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunRequest, RunStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_RunStreamClient = grpc.ServerStreamingClient[RunStreamResponse]

func (c *agentServiceClient) Name(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*NameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NameResponse)
	err := c.cc.Invoke(ctx, AgentService_Name_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, AgentService_Version_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RegisterServices(ctx context.Context, in *RegisterServicesRequest, opts ...grpc.CallOption) (*RegisterServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterServicesResponse)
	err := c.cc.Invoke(ctx, AgentService_RegisterServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SwitchSession(ctx context.Context, in *SwitchSessionRequest, opts ...grpc.CallOption) (*SwitchSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwitchSessionResponse)
	err := c.cc.Invoke(ctx, AgentService_SwitchSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SetPlanMode(ctx context.Context, in *SetPlanModeRequest, opts ...grpc.CallOption) (*SetPlanModeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPlanModeResponse)
	err := c.cc.Invoke(ctx, AgentService_SetPlanMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SetUserQuestionsService(ctx context.Context, in *SetUserQuestionsServiceRequest, opts ...grpc.CallOption) (*SetUserQuestionsServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetUserQuestionsServiceResponse)
	err := c.cc.Invoke(ctx, AgentService_SetUserQuestionsService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, AgentService_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) InjectMessage(ctx context.Context, in *InjectMessageRequest, opts ...grpc.CallOption) (*InjectMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InjectMessageResponse)
	err := c.cc.Invoke(ctx, AgentService_InjectMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DebugSnapshot(ctx context.Context, in *DebugSnapshotRequest, opts ...grpc.CallOption) (*DebugSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DebugSnapshotResponse)
	err := c.cc.Invoke(ctx, AgentService_DebugSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
type AgentServiceServer interface {
	Run(context.Context, *RunRequest) (*RunResponse, error)
	RunStream(*RunRequest, grpc.ServerStreamingServer[RunStreamResponse]) error
	Name(context.Context, *NameRequest) (*NameResponse, error)
	Version(context.Context, *VersionRequest) (*VersionResponse, error)
	RegisterServices(context.Context, *RegisterServicesRequest) (*RegisterServicesResponse, error)
	SwitchSession(context.Context, *SwitchSessionRequest) (*SwitchSessionResponse, error)
	SetPlanMode(context.Context, *SetPlanModeRequest) (*SetPlanModeResponse, error)
	SetUserQuestionsService(context.Context, *SetUserQuestionsServiceRequest) (*SetUserQuestionsServiceResponse, error)
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	// InjectMessage 将一条用户消息实时注入到当前运行的会话历史末端：
	// 模型在下一次 LLM 迭代即可看到，无需停止或等待本轮完成。
	InjectMessage(context.Context, *InjectMessageRequest) (*InjectMessageResponse, error)
	// DebugSnapshot 返回 agent 当前运行时的调试快照：会话历史（含实时注入的消息）、
	// token 用量、turn 计数与 plan/goal 状态。供 ADMIN API DEBUGGER 端点与自动化测试观察。
	DebugSnapshot(context.Context, *DebugSnapshotRequest) (*DebugSnapshotResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Run(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedAgentServiceServer) RunStream(*RunRequest, grpc.ServerStreamingServer[RunStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method RunStream not implemented")
}
func (UnimplementedAgentServiceServer) Name(context.Context, *NameRequest) (*NameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Name not implemented")
}
func (UnimplementedAgentServiceServer) Version(context.Context, *VersionRequest) (*VersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedAgentServiceServer) RegisterServices(context.Context, *RegisterServicesRequest) (*RegisterServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterServices not implemented")
}
func (UnimplementedAgentServiceServer) SwitchSession(context.Context, *SwitchSessionRequest) (*SwitchSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SwitchSession not implemented")
}
func (UnimplementedAgentServiceServer) SetPlanMode(context.Context, *SetPlanModeRequest) (*SetPlanModeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPlanMode not implemented")
}
func (UnimplementedAgentServiceServer) SetUserQuestionsService(context.Context, *SetUserQuestionsServiceRequest) (*SetUserQuestionsServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetUserQuestionsService not implemented")
}
func (UnimplementedAgentServiceServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedAgentServiceServer) InjectMessage(context.Context, *InjectMessageRequest) (*InjectMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InjectMessage not implemented")
}
func (UnimplementedAgentServiceServer) DebugSnapshot(context.Context, *DebugSnapshotRequest) (*DebugSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DebugSnapshot not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RunStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).RunStream(m, &grpc.GenericServerStream[RunRequest, RunStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_RunStreamServer = grpc.ServerStreamingServer[RunStreamResponse]

func _AgentService_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Name_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Name(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RegisterServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RegisterServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RegisterServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RegisterServices(ctx, req.(*RegisterServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SwitchSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SwitchSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SwitchSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SwitchSession(ctx, req.(*SwitchSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SetPlanMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPlanModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SetPlanMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SetPlanMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SetPlanMode(ctx, req.(*SetPlanModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SetUserQuestionsService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserQuestionsServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SetUserQuestionsService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SetUserQuestionsService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SetUserQuestionsService(ctx, req.(*SetUserQuestionsServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_InjectMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InjectMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).InjectMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_InjectMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).InjectMessage(ctx, req.(*InjectMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DebugSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DebugSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DebugSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DebugSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DebugSnapshot(ctx, req.(*DebugSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dsc.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _AgentService_Run_Handler,
		},
		{
			MethodName: "Name",
			Handler:    _AgentService_Name_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _AgentService_Version_Handler,
		},
		{
			MethodName: "RegisterServices",
			Handler:    _AgentService_RegisterServices_Handler,
		},
		{
			MethodName: "SwitchSession",
			Handler:    _AgentService_SwitchSession_Handler,
		},
		{
			MethodName: "SetPlanMode",
			Handler:    _AgentService_SetPlanMode_Handler,
		},
		{
			MethodName: "SetUserQuestionsService",
			Handler:    _AgentService_SetUserQuestionsService_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _AgentService_Shutdown_Handler,
		},
		{
			MethodName: "InjectMessage",
			Handler:    _AgentService_InjectMessage_Handler,
		},
		{
			MethodName: "DebugSnapshot",
			Handler:    _AgentService_DebugSnapshot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunStream",
			Handler:       _AgentService_RunStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dsc.proto",
}

const (
	LLMService_Chat_FullMethodName        = "/dsc.LLMService/Chat"
	LLMService_ChatStream_FullMethodName  = "/dsc.LLMService/ChatStream"
	LLMService_Name_FullMethodName        = "/dsc.LLMService/Name"
	LLMService_Version_FullMethodName     = "/dsc.LLMService/Version"
	LLMService_HealthCheck_FullMethodName = "/dsc.LLMService/HealthCheck"
)

// LLMServiceClient is the client API for LLMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LLMServiceClient interface {
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatStreamResponse], error)
	Name(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*NameResponse, error)
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type lLMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLLMServiceClient(cc grpc.ClientConnInterface) LLMServiceClient {
	return &lLMServiceClient{cc}
}

func (c *lLMServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, LLMService_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LLMService_ServiceDesc.Streams[0], LLMService_ChatStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LLMService_ChatStreamClient = grpc.ServerStreamingClient[ChatStreamResponse]

func (c *lLMServiceClient) Name(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*NameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NameResponse)
	err := c.cc.Invoke(ctx, LLMService_Name_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, LLMService_Version_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, LLMService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LLMServiceServer is the server API for LLMService service.
// All implementations must embed UnimplementedLLMServiceServer
// for forward compatibility.
type LLMServiceServer interface {
	Chat(context.Context, *ChatRequest) (*ChatResponse, error)
	ChatStream(*ChatRequest, grpc.ServerStreamingServer[ChatStreamResponse]) error
	Name(context.Context, *NameRequest) (*NameResponse, error)
	Version(context.Context, *VersionRequest) (*VersionResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedLLMServiceServer()
}

// UnimplementedLLMServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLLMServiceServer struct{}

func (UnimplementedLLMServiceServer) Chat(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedLLMServiceServer) ChatStream(*ChatRequest, grpc.ServerStreamingServer[ChatStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedLLMServiceServer) Name(context.Context, *NameRequest) (*NameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Name not implemented")
}
func (UnimplementedLLMServiceServer) Version(context.Context, *VersionRequest) (*VersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedLLMServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedLLMServiceServer) mustEmbedUnimplementedLLMServiceServer() {}
func (UnimplementedLLMServiceServer) testEmbeddedByValue()                    {}

// UnsafeLLMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LLMServiceServer will
// result in compilation errors.
type UnsafeLLMServiceServer interface {
	mustEmbedUnimplementedLLMServiceServer()
}

func RegisterLLMServiceServer(s grpc.ServiceRegistrar, srv LLMServiceServer) {
	// If the following call panics, it indicates UnimplementedLLMServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LLMService_ServiceDesc, srv)
}

func _LLMService_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).Chat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LLMServiceServer).ChatStream(m, &grpc.GenericServerStream[ChatRequest, ChatStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LLMService_ChatStreamServer = grpc.ServerStreamingServer[ChatStreamResponse]

func _LLMService_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_Name_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).Name(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LLMService_ServiceDesc is the grpc.ServiceDesc for LLMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LLMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dsc.LLMService",
	HandlerType: (*LLMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _LLMService_Chat_Handler,
		},
		{
			MethodName: "Name",
			Handler:    _LLMService_Name_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _LLMService_Version_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _LLMService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatStream",
			Handler:       _LLMService_ChatStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dsc.proto",
}

const (
	ToolService_ExecuteTool_FullMethodName     = "/dsc.ToolService/ExecuteTool"
	ToolService_ListTools_FullMethodName       = "/dsc.ToolService/ListTools"
	ToolService_ListContext_FullMethodName     = "/dsc.ToolService/ListContext"
	ToolService_SetInterconnect_FullMethodName = "/dsc.ToolService/SetInterconnect"
)

// ToolServiceClient is the client API for ToolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ToolServiceClient interface {
	ExecuteTool(ctx context.Context, in *ExecuteToolRequest, opts ...grpc.CallOption) (*ExecuteToolResponse, error)
	ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error)
	// ListContext 返回插件贡献的上下文片段（如技能索引），宿主将其拼接到 agent 的 system prompt；
	// content 为空表示该插件无贡献。旧插件未实现时返回 Unimplemented，宿主应跳过。
	ListContext(ctx context.Context, in *ListContextRequest, opts ...grpc.CallOption) (*ListContextResponse, error)
	// SetInterconnect 互通握手（机制 1/2/4）：宿主把挂载在本插件 client broker 上的
	// 聚合 LLM 服务、聚合 Tool 服务与插件通知服务的 serviceID 传给插件进程——插件经
	// 自身 broker.Dial 即可复用宿主 LLM 插件、调用宿主工具流水线（转发到任意工具插件）
	// 与事件总线，无需在插件启动时注入 env（避开握手时序）。
	// 旧插件未实现时返回 Unimplemented，宿主应跳过。
	SetInterconnect(ctx context.Context, in *InterconnectRequest, opts ...grpc.CallOption) (*InterconnectResponse, error)
}

type toolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewToolServiceClient(cc grpc.ClientConnInterface) ToolServiceClient {
	return &toolServiceClient{cc}
}

func (c *toolServiceClient) ExecuteTool(ctx context.Context, in *ExecuteToolRequest, opts ...grpc.CallOption) (*ExecuteToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteToolResponse)
	err := c.cc.Invoke(ctx, ToolService_ExecuteTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListToolsResponse)
	err := c.cc.Invoke(ctx, ToolService_ListTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) ListContext(ctx context.Context, in *ListContextRequest, opts ...grpc.CallOption) (*ListContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListContextResponse)
	err := c.cc.Invoke(ctx, ToolService_ListContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) SetInterconnect(ctx context.Context, in *InterconnectRequest, opts ...grpc.CallOption) (*InterconnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InterconnectResponse)
	err := c.cc.Invoke(ctx, ToolService_SetInterconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToolServiceServer is the server API for ToolService service.
// All implementations must embed UnimplementedToolServiceServer
// for forward compatibility.
type ToolServiceServer interface {
	ExecuteTool(context.Context, *ExecuteToolRequest) (*ExecuteToolResponse, error)
	ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error)
	// ListContext 返回插件贡献的上下文片段（如技能索引），宿主将其拼接到 agent 的 system prompt；
	// content 为空表示该插件无贡献。旧插件未实现时返回 Unimplemented，宿主应跳过。
	ListContext(context.Context, *ListContextRequest) (*ListContextResponse, error)
	// SetInterconnect 互通握手（机制 1/2/4）：宿主把挂载在本插件 client broker 上的
	// 聚合 LLM 服务、聚合 Tool 服务与插件通知服务的 serviceID 传给插件进程——插件经
	// 自身 broker.Dial 即可复用宿主 LLM 插件、调用宿主工具流水线（转发到任意工具插件）
	// 与事件总线，无需在插件启动时注入 env（避开握手时序）。
	// 旧插件未实现时返回 Unimplemented，宿主应跳过。
	SetInterconnect(context.Context, *InterconnectRequest) (*InterconnectResponse, error)
	mustEmbedUnimplementedToolServiceServer()
}

// UnimplementedToolServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedToolServiceServer struct{}

func (UnimplementedToolServiceServer) ExecuteTool(context.Context, *ExecuteToolRequest) (*ExecuteToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTool not implemented")
}
func (UnimplementedToolServiceServer) ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTools not implemented")
}
func (UnimplementedToolServiceServer) ListContext(context.Context, *ListContextRequest) (*ListContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListContext not implemented")
}
func (UnimplementedToolServiceServer) SetInterconnect(context.Context, *InterconnectRequest) (*InterconnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetInterconnect not implemented")
}
func (UnimplementedToolServiceServer) mustEmbedUnimplementedToolServiceServer() {}
func (UnimplementedToolServiceServer) testEmbeddedByValue()                     {}

// UnsafeToolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToolServiceServer will
// result in compilation errors.
type UnsafeToolServiceServer interface {
	mustEmbedUnimplementedToolServiceServer()
}

func RegisterToolServiceServer(s grpc.ServiceRegistrar, srv ToolServiceServer) {
	// If the following call panics, it indicates UnimplementedToolServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ToolService_ServiceDesc, srv)
}

func _ToolService_ExecuteTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).ExecuteTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_ExecuteTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).ExecuteTool(ctx, req.(*ExecuteToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_ListTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).ListTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_ListTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).ListTools(ctx, req.(*ListToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_ListContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).ListContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_ListContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).ListContext(ctx, req.(*ListContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_SetInterconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).SetInterconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_SetInterconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).SetInterconnect(ctx, req.(*InterconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ToolService_ServiceDesc is the grpc.ServiceDesc for ToolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dsc.ToolService",
	HandlerType: (*ToolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteTool",
			Handler:    _ToolService_ExecuteTool_Handler,
		},
		{
			MethodName: "ListTools",
			Handler:    _ToolService_ListTools_Handler,
		},
		{
			MethodName: "ListContext",
			Handler:    _ToolService_ListContext_Handler,
		},
		{
			MethodName: "SetInterconnect",
			Handler:    _ToolService_SetInterconnect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dsc.proto",
}

const (
	UserQuestionsService_Ask_FullMethodName = "/dsc.UserQuestionsService/Ask"
)

// UserQuestionsServiceClient is the client API for UserQuestionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UserQuestionsService 评审通道：agent 向宿主询问用户并阻塞等待回答（对齐 DSH user-questions）。
type UserQuestionsServiceClient interface {
	Ask(ctx context.Context, in *AskRequest, opts ...grpc.CallOption) (*AskResponse, error)
}

type userQuestionsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserQuestionsServiceClient(cc grpc.ClientConnInterface) UserQuestionsServiceClient {
	return &userQuestionsServiceClient{cc}
}

func (c *userQuestionsServiceClient) Ask(ctx context.Context, in *AskRequest, opts ...grpc.CallOption) (*AskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AskResponse)
	err := c.cc.Invoke(ctx, UserQuestionsService_Ask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserQuestionsServiceServer is the server API for UserQuestionsService service.
// All implementations must embed UnimplementedUserQuestionsServiceServer
// for forward compatibility.
//
// UserQuestionsService 评审通道：agent 向宿主询问用户并阻塞等待回答（对齐 DSH user-questions）。
type UserQuestionsServiceServer interface {
	Ask(context.Context, *AskRequest) (*AskResponse, error)
	mustEmbedUnimplementedUserQuestionsServiceServer()
}

// UnimplementedUserQuestionsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserQuestionsServiceServer struct{}

func (UnimplementedUserQuestionsServiceServer) Ask(context.Context, *AskRequest) (*AskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ask not implemented")
}
func (UnimplementedUserQuestionsServiceServer) mustEmbedUnimplementedUserQuestionsServiceServer() {}
func (UnimplementedUserQuestionsServiceServer) testEmbeddedByValue()                              {}

// UnsafeUserQuestionsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserQuestionsServiceServer will
// result in compilation errors.
type UnsafeUserQuestionsServiceServer interface {
	mustEmbedUnimplementedUserQuestionsServiceServer()
}

func RegisterUserQuestionsServiceServer(s grpc.ServiceRegistrar, srv UserQuestionsServiceServer) {
	// If the following call panics, it indicates UnimplementedUserQuestionsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserQuestionsService_ServiceDesc, srv)
}

func _UserQuestionsService_Ask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserQuestionsServiceServer).Ask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserQuestionsService_Ask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserQuestionsServiceServer).Ask(ctx, req.(*AskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserQuestionsService_ServiceDesc is the grpc.ServiceDesc for UserQuestionsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserQuestionsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dsc.UserQuestionsService",
	HandlerType: (*UserQuestionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ask",
			Handler:    _UserQuestionsService_Ask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dsc.proto",
}

const (
	PluginNotifyService_Notify_FullMethodName = "/dsc.PluginNotifyService/Notify"
)

// PluginNotifyServiceClient is the client API for PluginNotifyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginNotifyService 插件→宿主事件通知（互通机制 2）：插件进程经 broker
// 连接，把事件（含后台任务完成通知）发布到宿主事件总线，供 TUI/其他插件订阅。
type PluginNotifyServiceClient interface {
	Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error)
}

type pluginNotifyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginNotifyServiceClient(cc grpc.ClientConnInterface) PluginNotifyServiceClient {
	return &pluginNotifyServiceClient{cc}
}

func (c *pluginNotifyServiceClient) Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyResponse)
	err := c.cc.Invoke(ctx, PluginNotifyService_Notify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginNotifyServiceServer is the server API for PluginNotifyService service.
// All implementations must embed UnimplementedPluginNotifyServiceServer
// for forward compatibility.
//
// PluginNotifyService 插件→宿主事件通知（互通机制 2）：插件进程经 broker
// 连接，把事件（含后台任务完成通知）发布到宿主事件总线，供 TUI/其他插件订阅。
type PluginNotifyServiceServer interface {
	Notify(context.Context, *NotifyRequest) (*NotifyResponse, error)
	mustEmbedUnimplementedPluginNotifyServiceServer()
}

// UnimplementedPluginNotifyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginNotifyServiceServer struct{}

func (UnimplementedPluginNotifyServiceServer) Notify(context.Context, *NotifyRequest) (*NotifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Notify not implemented")
}
func (UnimplementedPluginNotifyServiceServer) mustEmbedUnimplementedPluginNotifyServiceServer() {}
func (UnimplementedPluginNotifyServiceServer) testEmbeddedByValue()                             {}

// UnsafePluginNotifyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginNotifyServiceServer will
// result in compilation errors.
type UnsafePluginNotifyServiceServer interface {
	mustEmbedUnimplementedPluginNotifyServiceServer()
}

func RegisterPluginNotifyServiceServer(s grpc.ServiceRegistrar, srv PluginNotifyServiceServer) {
	// If the following call panics, it indicates UnimplementedPluginNotifyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginNotifyService_ServiceDesc, srv)
}

func _PluginNotifyService_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginNotifyServiceServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginNotifyService_Notify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginNotifyServiceServer).Notify(ctx, req.(*NotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginNotifyService_ServiceDesc is the grpc.ServiceDesc for PluginNotifyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginNotifyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dsc.PluginNotifyService",
	HandlerType: (*PluginNotifyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Notify",
			Handler:    _PluginNotifyService_Notify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dsc.proto",
}

const (
	PluginHookService_BeforeTool_FullMethodName = "/dsc.PluginHookService/BeforeTool"
	PluginHookService_AfterTool_FullMethodName  = "/dsc.PluginHookService/AfterTool"
	PluginHookService_OnEvent_FullMethodName    = "/dsc.PluginHookService/OnEvent"
)

// PluginHookServiceClient is the client API for PluginHookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginHookService 插件侧钩子/事件订阅服务（互通机制 3）：插件在自身 gRPC
// server 上注册，宿主在工具流水线与事件广播时回调。使插件 A 能在不通知
// 主程序和其他插件的情况下，钩子式改变插件 B 的工具行为（拦截/改写）。
type PluginHookServiceClient interface {
	// 工具执行前（宿主 pre-execute 流水线内，按插件加载顺序调用）：可 veto
	// 或改写参数；veto 阻止执行。
	BeforeTool(ctx context.Context, in *BeforeToolRequest, opts ...grpc.CallOption) (*BeforeToolResponse, error)
	// 工具执行后：可改写结果/错误。
	AfterTool(ctx context.Context, in *AfterToolRequest, opts ...grpc.CallOption) (*AfterToolResponse, error)
	// 宿主事件订阅：含其他插件经 PluginNotifyService 发布的事件。
	OnEvent(ctx context.Context, in *OnEventRequest, opts ...grpc.CallOption) (*OnEventResponse, error)
}

type pluginHookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginHookServiceClient(cc grpc.ClientConnInterface) PluginHookServiceClient {
	return &pluginHookServiceClient{cc}
}

func (c *pluginHookServiceClient) BeforeTool(ctx context.Context, in *BeforeToolRequest, opts ...grpc.CallOption) (*BeforeToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeforeToolResponse)
	err := c.cc.Invoke(ctx, PluginHookService_BeforeTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginHookServiceClient) AfterTool(ctx context.Context, in *AfterToolRequest, opts ...grpc.CallOption) (*AfterToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AfterToolResponse)
	err := c.cc.Invoke(ctx, PluginHookService_AfterTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginHookServiceClient) OnEvent(ctx context.Context, in *OnEventRequest, opts ...grpc.CallOption) (*OnEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnEventResponse)
	err := c.cc.Invoke(ctx, PluginHookService_OnEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginHookServiceServer is the server API for PluginHookService service.
// All implementations must embed UnimplementedPluginHookServiceServer
// for forward compatibility.
//
// PluginHookService 插件侧钩子/事件订阅服务（互通机制 3）：插件在自身 gRPC
// server 上注册，宿主在工具流水线与事件广播时回调。使插件 A 能在不通知
// 主程序和其他插件的情况下，钩子式改变插件 B 的工具行为（拦截/改写）。
type PluginHookServiceServer interface {
	// 工具执行前（宿主 pre-execute 流水线内，按插件加载顺序调用）：可 veto
	// 或改写参数；veto 阻止执行。
	BeforeTool(context.Context, *BeforeToolRequest) (*BeforeToolResponse, error)
	// 工具执行后：可改写结果/错误。
	AfterTool(context.Context, *AfterToolRequest) (*AfterToolResponse, error)
	// 宿主事件订阅：含其他插件经 PluginNotifyService 发布的事件。
	OnEvent(context.Context, *OnEventRequest) (*OnEventResponse, error)
	mustEmbedUnimplementedPluginHookServiceServer()
}

// UnimplementedPluginHookServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginHookServiceServer struct{}

func (UnimplementedPluginHookServiceServer) BeforeTool(context.Context, *BeforeToolRequest) (*BeforeToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BeforeTool not implemented")
}
func (UnimplementedPluginHookServiceServer) AfterTool(context.Context, *AfterToolRequest) (*AfterToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AfterTool not implemented")
}
func (UnimplementedPluginHookServiceServer) OnEvent(context.Context, *OnEventRequest) (*OnEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OnEvent not implemented")
}
func (UnimplementedPluginHookServiceServer) mustEmbedUnimplementedPluginHookServiceServer() {}
func (UnimplementedPluginHookServiceServer) testEmbeddedByValue()                           {}

// UnsafePluginHookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginHookServiceServer will
// result in compilation errors.
type UnsafePluginHookServiceServer interface {
	mustEmbedUnimplementedPluginHookServiceServer()
}

func RegisterPluginHookServiceServer(s grpc.ServiceRegistrar, srv PluginHookServiceServer) {
	// If the following call panics, it indicates UnimplementedPluginHookServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginHookService_ServiceDesc, srv)
}

func _PluginHookService_BeforeTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeforeToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginHookServiceServer).BeforeTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginHookService_BeforeTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginHookServiceServer).BeforeTool(ctx, req.(*BeforeToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginHookService_AfterTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AfterToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginHookServiceServer).AfterTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginHookService_AfterTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginHookServiceServer).AfterTool(ctx, req.(*AfterToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginHookService_OnEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginHookServiceServer).OnEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginHookService_OnEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginHookServiceServer).OnEvent(ctx, req.(*OnEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginHookService_ServiceDesc is the grpc.ServiceDesc for PluginHookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginHookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dsc.PluginHookService",
	HandlerType: (*PluginHookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BeforeTool",
			Handler:    _PluginHookService_BeforeTool_Handler,
		},
		{
			MethodName: "AfterTool",
			Handler:    _PluginHookService_AfterTool_Handler,
		},
		{
			MethodName: "OnEvent",
			Handler:    _PluginHookService_OnEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dsc.proto",
}

const (
	FsObservationPolicyService_GetObservation_FullMethodName    = "/dsc.FsObservationPolicyService/GetObservation"
	FsObservationPolicyService_UpdateObservation_FullMethodName = "/dsc.FsObservationPolicyService/UpdateObservation"
)

// FsObservationPolicyServiceClient is the client API for FsObservationPolicyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FsObservationPolicyService 文件系統觀測策略服務
type FsObservationPolicyServiceClient interface {
	GetObservation(ctx context.Context, in *GetObservationRequest, opts ...grpc.CallOption) (*GetObservationResponse, error)
	UpdateObservation(ctx context.Context, in *UpdateObservationRequest, opts ...grpc.CallOption) (*UpdateObservationResponse, error)
}

type fsObservationPolicyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFsObservationPolicyServiceClient(cc grpc.ClientConnInterface) FsObservationPolicyServiceClient {
	return &fsObservationPolicyServiceClient{cc}
}

func (c *fsObservationPolicyServiceClient) GetObservation(ctx context.Context, in *GetObservationRequest, opts ...grpc.CallOption) (*GetObservationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetObservationResponse)
	err := c.cc.Invoke(ctx, FsObservationPolicyService_GetObservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fsObservationPolicyServiceClient) UpdateObservation(ctx context.Context, in *UpdateObservationRequest, opts ...grpc.CallOption) (*UpdateObservationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateObservationResponse)
	err := c.cc.Invoke(ctx, FsObservationPolicyService_UpdateObservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FsObservationPolicyServiceServer is the server API for FsObservationPolicyService service.
// All implementations must embed UnimplementedFsObservationPolicyServiceServer
// for forward compatibility.
//
// FsObservationPolicyService 文件系統觀測策略服務
type FsObservationPolicyServiceServer interface {
	GetObservation(context.Context, *GetObservationRequest) (*GetObservationResponse, error)
	UpdateObservation(context.Context, *UpdateObservationRequest) (*UpdateObservationResponse, error)
	mustEmbedUnimplementedFsObservationPolicyServiceServer()
}

// UnimplementedFsObservationPolicyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFsObservationPolicyServiceServer struct{}

func (UnimplementedFsObservationPolicyServiceServer) GetObservation(context.Context, *GetObservationRequest) (*GetObservationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetObservation not implemented")
}
func (UnimplementedFsObservationPolicyServiceServer) UpdateObservation(context.Context, *UpdateObservationRequest) (*UpdateObservationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateObservation not implemented")
}
func (UnimplementedFsObservationPolicyServiceServer) mustEmbedUnimplementedFsObservationPolicyServiceServer() {
}
func (UnimplementedFsObservationPolicyServiceServer) testEmbeddedByValue() {}

// UnsafeFsObservationPolicyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FsObservationPolicyServiceServer will
// result in compilation errors.
type UnsafeFsObservationPolicyServiceServer interface {
	mustEmbedUnimplementedFsObservationPolicyServiceServer()
}

func RegisterFsObservationPolicyServiceServer(s grpc.ServiceRegistrar, srv FsObservationPolicyServiceServer) {
	// If the following call panics, it indicates UnimplementedFsObservationPolicyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FsObservationPolicyService_ServiceDesc, srv)
}

func _FsObservationPolicyService_GetObservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FsObservationPolicyServiceServer).GetObservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FsObservationPolicyService_GetObservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FsObservationPolicyServiceServer).GetObservation(ctx, req.(*GetObservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FsObservationPolicyService_UpdateObservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateObservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FsObservationPolicyServiceServer).UpdateObservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FsObservationPolicyService_UpdateObservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FsObservationPolicyServiceServer).UpdateObservation(ctx, req.(*UpdateObservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FsObservationPolicyService_ServiceDesc is the grpc.ServiceDesc for FsObservationPolicyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FsObservationPolicyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dsc.FsObservationPolicyService",
	HandlerType: (*FsObservationPolicyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetObservation",
			Handler:    _FsObservationPolicyService_GetObservation_Handler,
		},
		{
			MethodName: "UpdateObservation",
			Handler:    _FsObservationPolicyService_UpdateObservation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dsc.proto",
}
